# Generated by Django 5.0.7 on 2024-07-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
