# Generated by Django 5.0.7 on 2024-07-13 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bankaccount', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('card_cvv', models.CharField(max_length=3)),
                ('card_expiry', models.DateField()),
                ('card_name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='bankaccount.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trx_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10)),
                ('trx_id', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('from_acc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_from', to='bankaccount.bankaccount')),
                ('to_acc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_to', to='bankaccount.bankaccount')),
            ],
        ),
    ]
