# Generated by Django 5.0.7 on 2024-07-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
