# Generated by Django 5.0.7 on 2024-07-17 13:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0003_bankaccount_daily_remaining_limit_and_more'),
        ('transaction', '0002_card_is_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('requested_at', models.DateTimeField(default=datetime.datetime(2024, 7, 17, 13, 11, 20, 583181, tzinfo=datetime.timezone.utc))),
                ('is_accepted', models.BooleanField(default=True)),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_from', to='bankaccount.bankaccount')),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to', to='bankaccount.bankaccount')),
            ],
        ),
    ]
