# Generated by Django 5.0.7 on 2024-07-17 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_requestmoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmoney',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
