# Generated by Django 5.0.7 on 2024-07-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_requestmoney_requested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmoney',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
