# Generated by Django 5.0.7 on 2024-07-17 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_requestmoney_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmoney',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestmoney',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
        ),
        migrations.AddField(
            model_name='requestmoney',
            name='transaction_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
