# Generated by Django 5.0.7 on 2024-07-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_requestmoney_is_rejected_requestmoney_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmoney',
            name='transaction_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
