# Generated by Django 5.0.7 on 2024-07-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_requestmoney_transaction_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='initiate_trx',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
