# Generated by Django 5.0.7 on 2024-07-13 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=16)),
                ('profession', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=16)),
                ('account_type', models.CharField(choices=[('Current', 'Current'), ('Islamic', 'Islamic')], max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('daily_limit', models.IntegerField(default=25000)),
                ('max_daily_limit', models.IntegerField(default=50000)),
                ('monthly_limit', models.IntegerField(default=500000)),
                ('max_monthly_limit', models.IntegerField(default=750000)),
                ('yearly_limit', models.IntegerField(default=1000000)),
                ('max_yearly_limit', models.IntegerField(default=1250000)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bankaccount.bankaccount')),
            ],
        ),
    ]
