# Generated by Django 5.0.7 on 2024-07-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
