# Generated by Django 5.0.7 on 2024-07-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0002_bankaccount_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='daily_remaining_limit',
            field=models.IntegerField(default=25000),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='monthly_remaining_limit',
            field=models.IntegerField(default=500000),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='yearly_remaining_limit',
            field=models.IntegerField(default=1000000),
        ),
    ]
