# Generated by Django 5.0.7 on 2024-07-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0004_bankaccount_otp_bankaccount_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='otp_attempts',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
